language: go
os:
  - linux
  - osx
go:
  - 1.4
  - tip
sudo: false
addons:
  apt:
    packages:
      - libcap-dev
install:
  - go get gopkg.in/hlandau/service.v1
  - cd $HOME/gopath/src/gopkg.in/hlandau/service.v1

